name: AutoXP
main: JackMD\AutoXP\Main
api: [4.0.0]
version: 2.1.0
author: JackMD
load: POSTWORLD
description: Say goodbye to xp orbs, now they come directly to your inventory.
website: https://github.com/KanekiLeChomeur/AutoXP
